Update PF Rule UUID Field Type
pfelk/pfelk pull request #325
Opened 2021-08-05 12:26 UTC by henworth

# Pull Request Template

## Description

The latest OPNsense update seemed to change the output type of the rule uuid field from an integer to an alphanumeric. Using the `WORD` grok pattern instead of `INT` will capture both scenarios.

Fixes #324 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

I used the Grok Debugger in Kibana to test the pattern change. I observed the change allowing the logged events in the issue to be parsed.

- [X] Original Configuration
- [X] Adjusted Configuration

**Test Configuration**:
* Elastic Stack Version: 7.13
* Linux Version/Type: Ubuntu 20.04
* Java Version: Built-in
* Elastic Stack Configuration Files:

## Checklist:

- [ ] Code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-08-08 02:20 UTC, a3ilson commented
Fix to OPNsense's UUID Rule Field

2021-08-08 13:42 UTC, henworth commented
I’m curious to know why this was closed?

2021-08-08 14:44 UTC, a3ilson commented
Inadvertently closed by mistake.

2021-08-09 13:16 UTC, a3ilson requested changes
This will fix OPNsesne but result in a breaking change for pfSense.  Revise to the following:

```%{INT:[rule][ruleset]},%{INT:[rule][id]}?,,%{WORD:[rule][uuid]},(%{WORD:[rule][uuid]}|%{INT:[rule][uuid]}),%{DATA:[interface][name]},(?<[event][reason]>\b[\w\-]+\b),%{WORD:[event][action]},%{WORD:[network][direction]},```

The above change add an option for INT or WORD which will enrich both pfSense or OPNsesne

2021-08-09 13:59 UTC, henworth commented
Would you be able to show an example of a pfSense event? The `WORD` pattern will match both a field containing only integers as well as one containing alphanumerics. See this capture from a [grok debug tool](https://grokdebugger.com/) (note that the semantic names are slightly modified as it doesn't support the nested structure):

<img width="1427" alt="Screen Shot 2021-08-09 at 9 44 29 AM" src="https://user-images.githubusercontent.com/1637082/128716244-6c91b686-991f-4e38-a829-927c6ad99959.png">

Each event parses correctly with only the `[rule][uuid]` field being different. The only characters that `INT` matches that `WORD` does not are leading `-`/`+`. So if pfSense has the potential to have those in this field we could alternatively use `DATA` as this would also cover both cases, similar to `[interface][name]`.

2021-08-09 15:30 UTC, a3ilson commented
@henworth - Here is a log from pfSense (I do not run pfSense but pulled this from a previously closed issue.  You are correct in that DATA will successfully enrich pfSense or OPNsense firewall log.  The next fix will be the mappings to recognize field as a data type vs INT.

```
%{INT:[rule][ruleset]},%{INT:[rule][id]}?,,%{DATA:[rule][uuid]},%{DATA:[interface][name]},(?<[event][reason]>\b[\w\-]+\b),%{WORD:[event][action]},%{WORD:[network][direction]},
```

2021-08-12 12:35 UTC, henworth commented
@a3ilson Change has been made as requested.

2021-08-12 18:59 UTC, a3ilson commented
Fixed UUID Rule (OPNsense) GROK pattern.

2021-08-12 19:01 UTC, a3ilson reviewed
Thanks!

2021-08-12 19:05 UTC, closed without merging